### ISSUE TITLE
realsense simulation in ignition gazebo

### ISSUE THREAD

**Issue by Sollimann** [TechnoYantra/ros2-igt#4]
Hey, does the `librealsense_gazebo_plugin.so` actually work in Ignition gazebo? :thinking: I thought it was only working in classic Gazebo?

Was looking for examples on how to simulate stereo camera and depth camera (e.g realsense) in Ignition Gazebo, and came across your URDF file here: https://github.com/TechnoYantra/ros2-igt/blob/main/igt_ignition/models/igt_one/igt_one.urdf :)

**Comment by jasmeet0915** [comment]
Hey, yes from our experience, the `librealsense_gazebo_plugin.so` does not work in ignition gazebo. The URDF you mentioned is not actually used in this project for spawning the robot model. It is from an older project which used classic gazebo for the same simulation.
In this project, we wanted to experiment with using SDF files for robot models. So we have used the above mentioned URDF to generate a SDF using `ign sdf` commands. You can find the final SDF [here](https://github.com/TechnoYantra/ros2-igt/blob/main/igt_ignition/models/igt_one/model.sdf). This SDF is used for spawning the robot model in ignition gazebo.
In the SDF, we have used the [color & depth camera sensor plugins](https://github.com/TechnoYantra/ros2-igt/blob/e70d16ff4486b0a136afc1f7a1ed6f60fb6340e3/igt_ignition/models/igt_one/model.sdf#L236) that come as part of `ign-sensors` for camera simulation.
